---
title: Content sidebar left
label: Content sidebar links
status: ready
context:
  header:
    file: logo.svg
    alt: Logo Overheid.nl, ga naar de startpagina
  sidebar:
    modifier: list--facet
    heading: Officiële bekendmakingen
    items:
      - text: <a href="#">Veelgestelde vragen</a>
