---
label: Blok (cards)
context:
  id: 1
  heading: Uitgelichte wetsvoorstellen
  subheading: Voor u geselecteerd
  headingType: h2
  intro: <p>Wetsvoorstellen worden uitgelicht als ze belangrijk kunnen zijn voor veel mensen. Bijvoorbeeld omdat het onderwerp nu in de samenleving speelt. Of omdat ze grote gevolgen hebben voor burgers of bedrijven. Wat is úw mening over deze voorstellen?</p>
  cards:
    - heading:
        label: Extra eisen aan thuisonderwijs als ouders geen geschikte school kunnen vinden
      subheading: Ministerie van Onderwijs, Cultuur en Wetenschap
      figure:
        figcaption: false
        source: false
        picture:
          src: ../../images/temp/illu-walkingdog.png
      labels:
        - label:
            text: Onderwijs
            modifier: label--large label--info
        - label:
            text: 16-07-2020
            modifier: label--large
      cta:
        label: Bekijk consultatie
    - heading:
        label: Wet deelgezag
      subheading: Ministerie van Justitie en Veiligheid
      figure:
        figcaption: false
        source: false
        picture:
          src: ../../images/temp/illu-walkingdog.png
      labels:
        - label:
            text: Gezien
            modifier: label--large label--info
        - label:
            text: 10-03-2021
            modifier: label--large
      cta:
        label: Bekijk consultatie
    - heading:
        label: Wijziging van o.a. het EKB WEB i.v.m. de uitwerking van het taalschakeltraject als onderwijsroute inburgering en de examinering Nt2
      subheading: Ministerie van Onderwijs, Cultuur en Wetenschap
      figure:
        figcaption: false
        source: false
        picture:
          src: ../../images/temp/illu-walkingdog.png
      labels:
        - label:
            text: Onderwijs
            modifier: label--large label--info
        - label:
            text: 10-03-2021
            modifier: label--large
      cta:
        label: Bekijk consultatie
