---
label: BodB - Zoekres. Lijst
status: prototype
context:
  header:
    file: logo.svg
    alt: Logo Overheid.nl, ga naar de startpagina
  mapContext:
    id: 1
    modifier: h-200
    controls: false
    kpm:
      id: 1
  mapContext2:
    id: 2
    modifier: h-200
    controls: false
    kpm:
      id: 2
  mapContext3:
    id: 3
    modifier: h-200
    controls: false
    kpm:
      id: 3
  voorschriftenContext:
    moreless: true
    morelessAmount: 5
    options:
    - id: checkbox-200
      text: Beleidsregel
      name: onderwerp
    - id: checkbox-201
      text: Algemeen verbindend voorschrift (verordering)
      name: onderwerp
    - id: checkbox-202
      text: Vergadering of stuk van het bestuur
      name: onderwerp
    - id: checkbox-203
      text: Ander besluit van algemene strekking
      name: onderwerp
    - id: checkbox-204
      text: Overige overheidsinformatie
      name: onderwerp
  voorlichtingContext:
    moreless: true
    morelessAmount: 5
    options:
    - id: checkbox-2023
      text: Afvalinzameling
      name: voorlichting
    - id: checkbox-2024
      text: Inspraak
      name: voorlichting
    - id: checkbox-2025
      text: Openingstijden
      name: voorlichting
    - id: checkbox-2026
      text: Verkiezingen
      name: voorlichting
    - id: checkbox-2027
      text: Andere voorlichtingsinformatie
      name: voorlichting
  rondomadresContext:
    moreless: true
    morelessAmount: 5
    options:
    - id: checkbox-2032
      text: Bouwen
      name: rondomadres
    - id: checkbox-2033
      text: Kappen
      name: rondomadres
    - id: checkbox-2034
      text: Slopen
      name: rondomadres
    - id: checkbox-2035
      text: Ruimtelijke ordening
      name: rondomadres
    - id: checkbox-2036
      text: Milieu
      name: rondomadres
    - id: checkbox-2037
      text: Uitweg en inrit
      name: rondomadres
    - id: checkbox-2038
      text: Reclame
      name: rondomadres
    - id: checkbox-2039
      text: Natuur
      name: rondomadres
    - id: checkbox-2040
      text: Brandveilig gebruik
      name: rondomadres
    - id: checkbox-2041
      text: Verkeersbesluit of -mededeling
      name: rondomadres
    - id: checkbox-2042
      text: Evenementenvergunning
      name: rondomadres
    - id: checkbox-2043
      text: Evenementmelding
      name: rondomadres
    - id: checkbox-2044
      text: Ruimtelijk plan of omgevingsdocument
      name: rondomadres
    - id: checkbox-2045
      text: Exploitatievergunning
      name: rondomadres
    - id: checkbox-2046
      text: Exploitatiemelding
      name: rondomadres
    - id: checkbox-2047
      text: Vergunning voor activiteiten op of in oppervlaktewater
      name: rondomadres
    - id: checkbox-2048
      text: Melding van activiteiten op of in oppervlaktewater
      name: rondomadres
    - id: checkbox-2049
      text: Andere vergunning
      name: rondomadres
    - id: checkbox-2050
      text: Andere beschikking
      name: rondomadres
    - id: checkbox-2051
      text: Andere melding
      name: rondomadres
  publicatieCustomRange:
    range: true
    placeholder: false
  publicatiedatumContext:
    moreless: true
    options:
    - id: radio-1112312312
      text: Vandaag
      name: publicatie
      checked: checked
    - id: radio-21231232
      text: Afgelopen week
      name: publicatie
    - id: radio-3312312312
      text: Afgelopen maand
      name: publicatie
    - id: radio-412312313
      text: Afgelopen 2 maanden
      name: publicatie
      disabled: disabled
    - id: radio-51222
      text: Zelf een periode kiezen
      name: publicatie
      linkedto: 1
  gebiedContext:
    moreless: true
    options:
    - id: radio-1111
      text: Berichten rond mijn adres
      name: publicaties
      checked: checked
    - id: radio-2222
      text: Berichten in mijn gemeente
      name: publicaties
  resultsContext:
    modifier: result--list--wide
    items:
    - title: AppelAfdeling 1.2.1. Algemene bepaling voor het sluiten van schriftelijke overeenkomsten onder bezwarende titel voor het verrichten van werken, leveringen of dienstent
      titleHeader: h2
      label: Nieuw vandaag
      text: Lorem ipsum dolor sit amet, consectetur adipisicing elit. Temporibus, obcaecati! Aperiam quasi debitis exercitationem ducimus! Eligendi, iusto, ut! Tempore ab sit eveniet fugit officia minus incidunt atque facilis saepe at!
      share: false
      buttons:
        - button: Bekijk publicatie
          type: primary
        - button: Bekijk op kaart
          type: secondary
          action: modal-1
          modal: true
    - title: AppelAfdeling 1.2.1. Algemene bepaling voor het sluiten van schriftelijke overeenkomsten onder bezwarende titel voor het verrichten van werken, leveringen of dienstent
      titleHeader: h2
      label: Nieuw vandaag
      text: Lorem ipsum dolor sit amet, consectetur adipisicing elit. Temporibus, obcaecati! Aperiam quasi debitis exercitationem ducimus! Eligendi, iusto, ut! Tempore ab sit eveniet fugit officia minus incidunt atque facilis saepe at!
      share: false
      buttons:
        - button: Bekijk publicatie
          type: primary
        - button: Bekijk op kaart
          type: secondary
          action: modal-2
          modal: true
    - title: AppelAfdeling 1.2.1. Algemene bepaling voor het sluiten van schriftelijke overeenkomsten onder bezwarende titel voor het verrichten van werken, leveringen of dienstent
      titleHeader: h2
      label: Nieuw vandaag
      text: Lorem ipsum dolor sit amet, consectetur adipisicing elit. Temporibus, obcaecati! Aperiam quasi debitis exercitationem ducimus! Eligendi, iusto, ut! Tempore ab sit eveniet fugit officia minus incidunt atque facilis saepe at!
      share: false
      buttons:
        - button: Bekijk publicatie
          type: primary
        - button: Bekijk op kaart
          type: secondary
          action: modal-3
          modal: true
  huisnrContext:
    modifier: input-text--medium
    labelmodifier: accent
    id: 1
    fieldLabel: Huisnummer + toev.
    fieldLabelVisible: true
    fieldInstruction:
    fieldPlaceholder: Bijv. 12A
    remove: true
  postcodeContext:
    modifier: input-text--medium
    labelmodifier: accent
    required: true
    id: 1
    fieldLabel: Postcode
    fieldLabelVisible: true
    fieldInstruction:
    fieldPlaceholder: 1234AB
    remove: true
  inputsubmitContext:
    id: 5432
    label: Verfijn uw zoekopdracht
    showLabel: false
    placeholder: Verfijn uw zoekopdracht
    button: Zoek
    modifierComponent: input-inputsubmit--s
    remove: true
  buttonswitchContext:
    text: banner
    buttons:
      - label: Lijst
        active: true
        icon: hamburger
      - label: Kaart
        icon: marker
  selectStraalContext:
    id: 1
    modifier: select-custom--large
    options:
      - label: 250 meter
        value: 250
        selected: true
      - label: 500 meter
        value: 500
      - label: 1000 meter
        value: 1000
      - label: 2000 meter
        value: 2000
      - label: Hele gemeente
        value: 9000
  contextNewsletter:
    required: true
    type: email
  jumbotronSaveContext:
    heading: Meld je aan voor de mail
    h: h2
    subheading: Deze zoekopdracht bewaren
    centered: true
    headingcentered: true
    intro: Schrijf u in en ontvang dagelijks een update in uw inbox over alles wat er bij u in de buurt gebeurt.
    inputsubmitSearchSaveContext:
      id: 102
      label: Uw e-mailadres
      showLabel: true
      placeholder: Uw e-mailadres
      button: Bevestigen
      required: true
  jumbotronChangeContext:
    heading: Welke buurt zoekt u?
    subheading: Wijzig uw zoekopdracht
    centered: true
    headingcentered: true
    huisnrContext:
      modifier: input-text--medium
      labelmodifier: accent
      id: 1
      fieldLabel: Huisnummer + toev.
      fieldLabelVisible: true
      fieldInstruction:
      fieldPlaceholder: Bijv. 12A
      remove: true
    postcodeContext:
      modifier: input-text--medium
      labelmodifier: accent
      id: 2
      fieldLabel: Postcode
      fieldLabelVisible: true
      fieldInstruction:
      fieldPlaceholder: Bijv. 12A
      required: true
      patterntype: zipcode
    selectContext:
      id: 876
      modifier: select-custom--large
      fieldLabel: Straal
      options:
        - label: 250m
          value: 250m
          selected: selected
        - label: 1km
          value: 1km
        - label: 2km
          value: 2km
    buttonSubmit:
      text: "Zoek opnieuw"
      button: true
      type: submit
      modifier: button--primary button--large
  jumbotron2Context:
    modifier: slim
    heading: Meld je aan voor de mail service
    h: h2
    subheading: Automatisch op de hoogte blijven van gebeurtenissen in uw buurt?
  tt1:
    id: 11
    content: Omgevingsvergunningen en meldingen met activiteiten zoals bouwen, slopen en kappen, verkeersbesluiten, evenementenvergunningen en dergelijke.
  tt2:
    id: 12
    content: Waaronder voorlichting over inspraak en verkiezingen voor de hele gemeente of openingstijden en huisafval.
  tt3:
    id: 13
  tt4:
    id: 14
    content: Waaronder beleidsregels of stukken van het bestuur voor de hele gemeente of besluiten van algemene strekking.
  tt5:
    id: 15
  tt6:
    id: 16


