---
title: Zoekresultaten wetten.nl
label: Zoekresultaten wetten.nl
status: wip
context:
  header:
    file: logo.svg
    alt: Logo Overheid.nl, ga naar de startpagina
  spoedpublicatiemelding:
    modifier: alert--info
    text: Lorem ipsum dolor sit amet, consectetur adipisicing elit.
  actieblok:
    title: ''
    intro: ''
    modifier: browse--icons
    items:
      - link: '#'
        text: Alles openklappen
      - link: '#'
        text: Alles dichtklappen
      - link: '#'
        text: Alles aanvinken
      - link: '#'
        text: Alles uitvinken
      - link: '#'
        text: Toon aangevinkte elementen
