title: Test
status: ready
context:
  file: logo.svg
  alt: Logo Overheid.nl, ga naar de startpagina
  nav: true
  youAreHere:
    - text: Register voor overheidsinstanties
  hamburgerButtonText: Menu
  navLinks:
    - url: '#'
      text: Zoeken
    - url: '#'
      text: uitgebreid zoeken
  skipLinks:
    - url: '#content'
      text: Direct naar content
  headerMore:
    - title: Berichten over uw buurt
      description: Zoals bouwplannen en verkeersmaatregelen.
      links:
        - url: 'https://www.overheid.nl/berichten-over-uw-buurt'
          text: Zoek naar berichten
        - url: 'https://www.overheid.nl/berichten-over-uw-buurt#meld-u-aan-voor-de-e-mailservice'
          text: Blijf op de hoogte
    - title: Dienstverlening
      description: Zoals belastingen, uitkeringen en subsidies.
      links:
        - url: 'https://www.overheid.nl/dienstverlening'
          text: Naar dienstverlening
    - title: Beleid & regelgeving
      description: Officiële publicaties van de overheid.
      links:
        - url: 'https://www.overheid.nl/beleid-en-regelgeving'
          text: Naar beleid & regelgeving
    - title: Contactgegevens overheden
      description: Adressen en contactpersonen van overheidsorganisaties.
      links:
        - url: 'https://organisaties.overheid.nl/'
          text: Naar overheidsorganisaties
variants:
  - name: With Meta Nav
    label: met Meta navigatie
    context:
      metaLinks:
      - href: '#'
        text: Attenderen
      - href: '#'
        text: Contactgegevens
      - url: "#"
        text: Uitloggen
        class: button button--logout
  - name: With Profile
    label: met Profiel
    context:
      metaLinks:
      - nonlink: true
        text: Gebruiker
        class: icon icon--profile
      - profile: true
        profileContext:
          loggedIn: true
          textLoggedIn: Mijn account
          options:
            - text: Mijn abonnementen
              url: '#'
            - text: Inloggen
              url: '#'
  - name: met Alert notificatie
    context:
      alertNotification:
        modifier: alert--warning
        text: Wegens technisch onderhoud is de website op donderdag 2 januari 2020 vanaf 17:00 verminderd beschikbaar.
  - name: Omgeving 'dev'
    context:
      environment: dev
  - name: Omgeving 'test'
    context:
      environment: test
  - name: Omgeving 'acc'
    context:
      environment: acc

