---
label: SONL - Veelgestelde vragen
status: ready
context:
  header:
    file: logo.svg
    alt: Logo Overheid.nl, ga naar de startpagina
    youAreHere:
    - text: StandaardenOverheid.nl
    skipLinks:
      - url: '#content'
        text: Direct naar content
    navLinks:
    - url: '#'
      text: OWMS
      className: is-active
    - url: '#'
      text: Contentmodellen
    - url: '#'
      text: Nieuws
    - url: '#'
      text: Contact
    - url: '#'
      text: Sitemap
    - url: '#'
      text: Toegankelijkheid
  breadcrumb:
    breadcrumb:
    - text: Home
      url: '#'
    - text: OWMS
      url: '#'
    - text: Veelgestelde vragen
  navToeContext:
    id: 3
    items:
    - title: OWMS
      sub: true
      active: true
      subItems:
        - stitle: OWMS 4.0
          href: "/1"
        - stitle: OWMS 3.5
          href: "/2"
        - stitle: Beheer
          href: "/3"
        - stitle: Veelgestelde vragen
          href: "/4"
          sactive: true
        - stitle: SRU-koppelvlak zoekdienst
          href: "/4"
        - stitle: Publicaties
          href: "/5"
  accordion:
    item1:
      headerId: header12
      headerLabel: In hoeverre is het verplicht OWMS toe te passen?
      contentId: con12
    item2:
      headerId: header13
      headerLabel: Voor wie is OWMS bedoeld?
      contentId: con13
    item3:
      headerId: header14
      headerLabel: Voor mijn applicatie heb ik behoefte aan een nieuwe waardelijst. Wat nu?
      contentId: con14
    item4:
      headerId: header15
      headerLabel: Is het mogelijk om zelf inspraak te krijgen in de door-ontwikkeling van de standaard?
      contentId: con15
    item5:
      headerId: header16
      headerLabel: Voldoet mijn metadata, die aan OWMS 3.5 voldoet, nu ook aan OWMS 4.0?
      contentId: con16
  contact:
    text: 'Bij vragen of opmerkingen, neem contact met ons op via e-mailadres: <a href="mailto:ContactOWMS@overheid.nl">ContactOWMS@overheid.nl</a>'