title: Table
label: Tabel
status: ready
context:
  label: default
  caption: Deze tabel bevat teamleden van KOOP Overheid.nl
  items:
    - item:
      - column:
        type:
        value: 1
      - column:
        type: Voornaam
        value: John 
      - column:
        type: Achternaam
        value: Doe
      - column:
        type: Woonplaats
        value: City
    - item:
      - column:
        type:
        value: 2
      - column:
        type: Voornaam
        value: Pieter
      - column:
        type: Achternaam
        value: Post
      - column:
        type: Woonplaats
        value: City
    - item:
      - column:
        type:
        value: 3
      - column:
        type: Voornaam
        value: Test
      - column:
        type: Achternaam
        value: Test
      - column:
        type: Woonplaats
        value: Test
variants:
  - name: Fixed columns
    label: Vaste kolommen
    context:
      caption: Deze tabel bevat teamleden van KOOP Overheid.nl
      items:
        - item:
          - column:
            type:
            value: 1
          - column:
            thclass: u-columnwidth-30p
            type: Voornaam
            value: John
          - column:
            thclass: u-columnwidth-30p
            type: Achternaam
            value: Doe
          - column:
            thclass: u-columnwidth-30p
            type: Woonplaats
            value: City
        - item:
          - column:
            type:
            value: 2
          - column:
            type: Voornaam
            value: Pieter
          - column:
            type: Achternaam
            value: Post
          - column:
            type: Woonplaats
            value: City
        - item:
          - column:
            type:
            value: 3
          - column:
            type: Voornaam
            value: Test
          - column:
            type: Achternaam
            value: Test
          - column:
            type: Woonplaats
            value: Test
  - name: Multilevel
    label: Meerlaags
    context:
      modifier:
      caption: Deze tabel bevat teamleden van KOOP Overheid.nl
      multilevel: true
      multilevels:
        - title: 2
        - title: 3
        - title: 4
        - title: 5
  - name: with Caption
    label: met Caption
    context:
      modifier:
      caption: Deze tabel bevat teamleden van KOOP Overheid.nl
  - name: with Description
    label: met Omschrijving
    context:
      modifier:
      describedby: described123
      tableDescription: Deze tabel bevat een extra uitleg onder de tabel.
  - name: borderless
    label: Zonder border
    context:
      modifier: table--borderless
  - name: Rotated headers
    label: Gedraaide headers
    context:
      rotated: true
      caption: Deze tabel bevat headers die verticaal staan
  - name: striped
    label: Strepen
    context:
      modifier: table--striped
  - name: condensed
    label: Dun
    context:
      modifier: table--condensed
  - name: hover
    label: met Hovereffect
    context:
      modifier: table--hover
  - name: Header highlighted
    label: Header uitgelicht
    context:
      modifier: table--headerhighlight
  - name: datakalender
    context:
      caption:
      items:
        - item:
          - column:
            type: Data-eigenaar
            value: ZBO | Centraal Bureau voor de Statistiek
          - column:
            type: Soort organisatie
            value: zelfstandig
          - column:
            type: Valt onder
            value: zelfstandig
          - column:
            type: Datasets
            value: 4,504
          - column:
            type: Link-kwaliteit
            value: 9065 / 9066 - 99.99%
          - column:
            type: Status
            value: alles werkt
            cellType: status--green
          - column:
            type: Exporteren
            value: pdf
            download: true
        - item:
          - column:
            type: Data-eigenaar
            value: Leveranciers (geen overheid) | Zonatlas NL B.V
          - column:
            type: Soort organisatie
            value: Stichting
          - column:
            type: Valt onder
            value: Regionaal
          - column:
            type: Datasets
            value: 1
          - column:
            type: Link-kwaliteit
            value: 0 / 0 - 0%
          - column:
            type: Status
            value: sommige werken
            cellType: status--orange
          - column:
            type: Exporteren
            value: csv
            download: true
        - item:
          - column:
            type: Data-eigenaar
            value: Jeroen
          - column:
            type: Soort organisatie
            value: BV
          - column:
            type: Valt onder
            value: Niemand
          - column:
            type: Datasets
            value: veel
          - column:
            type: Link-kwaliteit
            value: top
          - column:
            type: Status
            value: niets werkt
            cellType: status--red
          - column:
            type: Exporteren
            value: xml
            download: true
        - item:
          - column:
            type: Data-eigenaar
            value: ZBO | Centraal Bureau voor de Statistiek
          - column:
            type: Soort organisatie
            value: zelfstandig
          - column:
            type: Valt onder
            value: zelfstandig
          - column:
            type: Datasets
            value: 4,504
          - column:
            type: Link-kwaliteit
            value: 9065 / 9066 - 99.99%
          - column:
            type: Status
            value: alles werkt
            cellType: status--green
          - column:
            type: Exporteren
            value: pdf
            download: true
        - item:
          - column:
            type: Data-eigenaar
            value: Leveranciers (geen overheid) | Zonatlas NL B.V
          - column:
            type: Soort organisatie
            value: Stichting
          - column:
            type: Valt onder
            value: Regionaal
          - column:
            type: Datasets
            value: 1
          - column:
            type: Link-kwaliteit
            value: 0 / 0 - 0%
          - column:
            type: Status
            value: sommige werken
            cellType: status--orange
          - column:
            type: Exporteren
            value: csv
            download: true
        - item:
          - column:
            type: Data-eigenaar
            value: Jeroen
          - column:
            type: Soort organisatie
            value: BV
          - column:
            type: Valt onder
            value: Niemand
          - column:
            type: Datasets
            value: veel
          - column:
            type: Link-kwaliteit
            value: top
          - column:
            type: Status
            value: niets werkt
            cellType: status--red
          - column:
            type: Exporteren
            value: xml
            download: true
        - item:
          - column:
            type: Data-eigenaar
            value: ZBO | Centraal Bureau voor de Statistiek
          - column:
            type: Soort organisatie
            value: zelfstandig
          - column:
            type: Valt onder
            value: zelfstandig
          - column:
            type: Datasets
            value: 4,504
          - column:
            type: Link-kwaliteit
            value: 9065 / 9066 - 99.99%
          - column:
            type: Status
            value: alles werkt
            cellType: status--green
          - column:
            type: Exporteren
            value: pdf
            download: true
        - item:
          - column:
            type: Data-eigenaar
            value: Leveranciers (geen overheid) | Zonatlas NL B.V
          - column:
            type: Soort organisatie
            value: Stichting
          - column:
            type: Valt onder
            value: Regionaal
          - column:
            type: Datasets
            value: 1
          - column:
            type: Link-kwaliteit
            value: 0 / 0 - 0%
          - column:
            type: Status
            value: sommige werken
            cellType: status--orange
          - column:
            type: Exporteren
            value: csv
            download: true
        - item:
          - column:
            type: Data-eigenaar
            value: Jeroen
          - column:
            type: Soort organisatie
            value: BV
          - column:
            type: Valt onder
            value: Niemand
          - column:
            type: Datasets
            value: veel
          - column:
            type: Link-kwaliteit
            value: top
          - column:
            type: Status
            value: niets werkt
            cellType: status--red
          - column:
            type: Exporteren
            value: xml
            download: true
  - name: Met Topbar
    context:
      topbar:
        items:
          - text: Open in nieuw scherm
            href: www.overheid.nl
            class: icon icon--fullscreen

