---
title: BWB - TT - Zoeken
label: BWB - TT - Zoeken
status: ready
context:
  headerContext:
    file: logo.svg
    alt: Overheid.nl logo
    youAreHere:
    - text: Wettenbank
    navLinks:
      - url: '#'
        text: Eenvoudig zoeken
      - url: '#'
        text: Uitgebreid zoeken
      - url: '#'
        text: Toekomstige teksten zoeken
        className: is-active
      - url: '#'
        text: Zoeken in EU-richtlijnen
  breadcrumb:
    title: "U bent hier:"
    breadcrumb:
      - text: Toekomstige teksten
  alertToekomstig:
    text: U zoekt in toekomstige teksten. <a href="#">Wat betekent dit?</a>
  sc1:
    id: ZoekOp_BronPublicatie
    modifier: select-custom--width-s
    options:
      - label: Publicatie
        value: ''
        selected: selected
      - label: Staatsblad
        value: stb
      - label: Staatscourant
        value: stcrt
      - label: Staatscourant-supplement
        value: Supplement-Stcrt
      - label: Tractatenblad
        value: Trb
      - label: Uitleg
        value: Uitleg
      - label: Infobulletin
        value: Infob
      - label: PBO blad
        value: Vbbo
  inputtext1:
    id: ZoekOp_BronPublicatieJaar
    cleanID: true
    fieldLabel: Publicatiejaar
    fieldVisibility: false
    fieldInstruction:
    fieldPlaceholder: 'Jaar'
    modifier: input--xsmall
  inputtext2:
    id: ZoekOp_BronPublicatieNummer
    cleanID: true
    fieldLabel: Nummer
    fieldVisibility: false
    fieldInstruction:
    fieldPlaceholder: 'Nr'
    modifier: input--small
  tt1:
    id: 1
    label: Help?
    content: U kunt hieronder één, meerdere of alle soorten regelingen aanvinken.
  tt2:
    id: 2
    label: Help?
    content: Standaard worden Archiefselectielijsten niet doorzocht. U kunt deze doorzoeken via Uitgebreid zoeken.
  tt3:
    id: 3
    label: Help?
    content: Toon ook regelingen die enkel op Bonaire, Sint Eustatius en Saba van toepassing zijn.
  tt4:
    id: 4
    label: Help?
    content: Toon uitsluitend regelingen die enkel op Bonaire, Sint Eustatius en Saba van toepassing zijn.
  tt45:
    id: 45
    label: Help?
    content: U kunt hier zoeken op een of meer woorden die voorkomen in de titel of in de tekst. Wanneer u 'Exact zoeken' uitvinkt, dan zoekt u ook op spellingsvarianten en woordsamenstellingen, e.d.
  tt5:
    id: 5
    label: Help?
    content: U zoekt hier op woord(en) in de citeertitel en het opschrift van de regelingen. U kunt ook populaire benamingen invoeren, zoals 'Flexwet'. Wilt u zoeken op de afkorting of op de volledige regelingtitel vink dan het betreffende vakje aan.
  tt6:
    id: 6
    label: Help?
    content: "U zoekt hier op woord(en) in de tekst van de regelingen. Als u wilt dat meerdere woorden voorkomen in de tekst, gebruikt u de EN-operator, bijv. ‘gezondheid EN veiligheid’. Als u wilt dat tenminste één van de woorden voorkomt in de tekst, gebruikt u de OF-operator, bijv. ‘gezondheid OF veiligheid’. Indien u ook op woordsamenstellingen wilt zoeken, dan kunt u gebruik maken van een '*'. Bijvoorbeeld met de zoekterm: ‘milieu*’, vindt u ook ‘milieuvergunning’ en ‘milieuplan’."
  tt7:
    id: 7
    label: Help?
    content: U kunt zoeken op alle voorkomende artikelnummers, zoals “1”, “1.1”, “1:1”.
  tt8:
    id: 8
    label: Help?
    content: U kunt zoeken in de regelingen zoals geldend op de datum vandaag (standaard), of een eerdere datum. Regelingen die materieel zijn uitgewerkt worden standaard niet doorzocht, tenzij u het vakje aanvinkt.
  tt9:
    id: 9
    label: Help?
    content: Regelingen die niet zijn ingetrokken of vervallen maar feitelijk geen werking meer hebben, worden standaard niet doorzocht. Wilt u dit wel, vink dan dit vakje aan.
  tt19:
    id: 19
    label: Help?
    content: U zoekt hier op het dossiernummer van de Kamerstukken behorend bij zowel de oorspronkelijke versie van de regeling als de wijzigingen daarin. Bijvoorbeeld ‘34702’.
  tt18:
    id: 18
    label: Help?
    content: U zoekt hier op de identifier van een in wetten.overheid.nl opgenomen regeling. Bijvoorbeeld ‘BWBR0001840’ voor de Grondwet en ‘BWBV0005225’ voor het Europees Vestingsverdrag.
  tt20:
    id: 20
    label: Help?
    content: U zoek hier op het (departementaal) kenmerk van de regeling.
  btnSubmit:
    text: Zoeken
  btnReset:
    text: Wis scherm
    inputButton: false
    inputSubmit: false
    type: button
    action: '#'
    anchor: true
  dp1:
    id: ZoekOp_Geldigheidsdatum
    cleanId: true
