---
title: BWB - TT - Zoekresultaten
label: BWB - TT - Zoekresultaten
status: ready
context:
  header:
    file: logo.svg
    alt: Overheid.nl logo
    youAreHere:
      - text: Wettenbank
    navLinks:
      - url: '#'
        text: Eenvoudig zoeken
      - url: '#'
        text: Uitgebreid zoeken
      - url: '#'
        text: Zoeken in EU-richtlijnen
      - url: '#'
        text: Toekomstige teksten
        className: is-active
  breadcrumb:
    title: "U bent hier:"
    breadcrumb:
      - text: Uitgebreid zoeken
        url: '#'
      - text: Zoekresultaten
  alertToekomstig:
    text: U zoekt in toekomstige teksten. <a href="#">Wat betekent dit?</a>
  spoedpublicatiemelding:
    modifier: alert--info
    text: Lorem ipsum dolor sit amet, consectetur adipisicing elit.
  actieblok:
    title: 'Acties'
    intro: ''
    modifier: browse--icons
    items:
      - link: '#'
        text: Alles openklappen
        icon: icon-plus.svg
      - link: '#'
        text: Alles dichtklappen
        icon: icon-minus.svg
      - link: '#'
        text: Alles uitvinken
        icon: icon-uncheckall.svg
        id: unmarkallAnchor
      - link: '/selectie/?g=18-05-2021&z=18-05-2021'
        class: js-aangevinkteelementen
        text: Toon aanvinkte elementen
        icon: icon-arrow-right.svg
  pageactions:
    items:
      - link: '#'
        text: downloaden
        icon: icon-download-black.svg
        title: Opslaan als RTF-bestand
      - link: '#'
        text: printen
        icon: icon-print.svg
        title: Afdrukken
  resultlist:
    item1:
      title: Omgevingswet
      href: '#'
      labelsSecondair:
        - labelSecondair: Regeling treed in werking op nader te bepalen tijdstip
          labelSecondairType: warning
      amountResults: (663 artikelen)
      hiddenInputs:
        - id:
          class: data-id
          value: http://wetten.overheid.nl/id/BWBR0032203/2019-04-18/0
        - id:
          class: data-nr
          value: 0
        - id:
          class: locationurl
          value: https://wetten.overheid.nl/uitgebreid_zoeken/zoekresultaat/rs/2,3,4,5,7/titelf/1/tekstf/1/wti/0/artnrb/0/d/17-02-2021/zd/17-02-2021/dx/0/ds/0/dt/1/db/1
      collapsible:
        id: 3
        heading: 1 relevante elementen
        modifier: collapsible--small
    item2:
      title: Invoeringswet Omgevingswet
      href: '#'
      labelsSecondair:
        - labelSecondair: Regeling treed in werking op nader te bepalen tijdstip
          labelSecondairType: warning
      amountResults: (98 artikelen)
      hiddenInputs:
        - id:
          class: data-id
          value: http://wetten.overheid.nl/id/BWBR0032898/2019-04-18/0
        - id:
          class: data-nr
          value: 1
        - id:
          class: locationurl
          value: https://wetten.overheid.nl/uitgebreid_zoeken/zoekresultaat/rs/2,3,4,5,7/titelf/1/tekstf/1/wti/0/artnrb/0/d/17-02-2021/zd/17-02-2021/dx/0/ds/0/dt/1/db/1
      collapsible:
        id: 23
        heading: 1 relevante elementen
        modifier: collapsible--small
    item3:
      title: Wet milieubeheer
      href: '#'
      labelsSecondair:
        - labelSecondair: Tekst geldend vanaf 01-07-2021 t/m 31-12-2021
          labelSecondairType: info
      amountResults: (663 artikelen)
      hiddenInputs:
        - id:
          class: data-id
          value: http://wetten.overheid.nl/id/BWBR0032898/2019-04-18/0
        - id:
          class: data-nr
          value: 1
        - id:
          class: locationurl
          value: https://wetten.overheid.nl/uitgebreid_zoeken/zoekresultaat/rs/2,3,4,5,7/titelf/1/tekstf/1/wti/0/artnrb/0/d/17-02-2021/zd/17-02-2021/dx/0/ds/0/dt/1/db/1
      collapsible:
        id: 23
        heading: 1 relevante elementen
        modifier: collapsible--small
    item4:
      title: Wet milieubeheer
      href: '#'
      labelsSecondair:
        - labelSecondair: Tekst geldend vanaf 01-01-2022
          labelSecondairType: info
      amountResults: (663 artikelen)
      hiddenInputs:
        - id:
          class: data-id
          value: http://wetten.overheid.nl/id/BWBR0032898/2019-04-18/0
        - id:
          class: data-nr
          value: 1
        - id:
          class: locationurl
          value: https://wetten.overheid.nl/uitgebreid_zoeken/zoekresultaat/rs/2,3,4,5,7/titelf/1/tekstf/1/wti/0/artnrb/0/d/17-02-2021/zd/17-02-2021/dx/0/ds/0/dt/1/db/1
      collapsible:
        id: 23
        heading: 1 relevante elementen
        modifier: collapsible--small
    item5:
      title: Wet milieubeheer
      href: '#'
      labelsSecondair:
        - labelSecondair: Regeling treed in werking op nader te bepalen tijdstip
          labelSecondairType: info
      amountResults: (663 artikelen)
      hiddenInputs:
        - id:
          class: data-id
          value: http://wetten.overheid.nl/id/BWBR0032898/2019-04-18/0
        - id:
          class: data-nr
          value: 1
        - id:
          class: locationurl
          value: https://wetten.overheid.nl/uitgebreid_zoeken/zoekresultaat/rs/2,3,4,5,7/titelf/1/tekstf/1/wti/0/artnrb/0/d/17-02-2021/zd/17-02-2021/dx/0/ds/0/dt/1/db/1
      collapsible:
        id: 23
        heading: 1 relevante elementen
        modifier: collapsible--small
    item6:
      title: Wet belastingen op miliuegrondslag
      href: '#'
      labelsSecondair:
        - labelSecondair: Regeling treed in werking op nader te bepalen tijdstip
          labelSecondairType: info
      amountResults: (663 artikelen)
      hiddenInputs:
        - id:
          class: data-id
          value: http://wetten.overheid.nl/id/BWBR0032898/2019-04-18/0
        - id:
          class: data-nr
          value: 1
        - id:
          class: locationurl
          value: https://wetten.overheid.nl/uitgebreid_zoeken/zoekresultaat/rs/2,3,4,5,7/titelf/1/tekstf/1/wti/0/artnrb/0/d/17-02-2021/zd/17-02-2021/dx/0/ds/0/dt/1/db/1
      collapsible:
        id: 23
        heading: 1 relevante elementen
        modifier: collapsible--small
  resultlist2:
    item1:
      title: Aanvullingsbesluit natuur Omgevingswet
      href: '#'
      amountResults: (101 artikelen)
      labelsSecondair:
        - labelSecondair: Regeling treed in werking op nader te bepalen tijdstip
          labelSecondairType: warning
      collapsible:
        id: 33
        heading: 5 relevante elementen
        modifier: collapsible--small
      hiddenInputs:
        - id:
          class: data-id
          value: http://wetten.overheid.nl/id/BWBV0005592/1948-12-02/0
        - id:
          class: data-nr
          value: 0
        - id:
          class: locationurl
          value: https://wetten.overheid.nl/uitgebreid_zoeken/zoekresultaat/titelf/1/tekstf/1/wti/0/artnrb/0/d/17-02-2021/zd/17-02-2021/dx/0/ds/0/dt/1/db/1
    item2:
      title: Besluit capaciteitsverdeling hoofdspoorweginfrastructuur
      href: '#'
      labelsSecondair:
        - labelSecondair: Tekst geldend vanaf nader te bepalen tijdstip
          labelSecondairType: info
      amountResults: (17 artikelen)
      collapsible:
        id: 33
        heading: 2 relevante elementen
        modifier: collapsible--small
      hiddenInputs:
        - id:
          class: data-id
          value: http://wetten.overheid.nl/id/BWBV0005592/1948-12-02/0
        - id:
          class: data-nr
          value: 0
        - id:
          class: locationurl
          value: https://wetten.overheid.nl/uitgebreid_zoeken/zoekresultaat/titelf/1/tekstf/1/wti/0/artnrb/0/d/17-02-2021/zd/17-02-2021/dx/0/ds/0/dt/1/db/1
  resultlist3:
    item1:
      title: Omgevingsregeling
      href: '#'
      amountResults: (12 artikelen)
      labelsSecondair:
        - labelSecondair: Regeling treed in werking op nader te bepalen tijdstip
          labelSecondairType: warning
      collapsible:
        id: 33
        heading: 3 relevante elementen
        modifier: collapsible--small
      hiddenInputs:
        - id:
          class: data-id
          value: http://wetten.overheid.nl/id/BWBV0005592/1948-12-02/0
        - id:
          class: data-nr
          value: 0
        - id:
          class: locationurl
          value: https://wetten.overheid.nl/uitgebreid_zoeken/zoekresultaat/titelf/1/tekstf/1/wti/0/artnrb/0/d/17-02-2021/zd/17-02-2021/dx/0/ds/0/dt/1/db/1