title: sort
label: Pagina sorteren
context:
  options:
    - label: Datum
      href: '#'
      active: is-active
    - label: Titel
      href: '#'
  amountPerPageOptions:
    - amount: 10
      active: true
      pressed: true
      href: '/10'
    - amount: 20
      href: '/20'
    - amount: 50
      href: '/50'
variants:
  - name: with amount
    label: met Aantal resultaten
    context:
      columns: true
      amountPerPageFilter: true
      buttonDownload: false
  - name: with Download
    label: met button Download
    context:
      columns: true
      buttonDownload: true

