---
label: PLOOI - Homepage TXT
status: ready
context:
  header:
    file: logo.svg
    alt: Logo Overheid.nl, ga naar de startpagina
    language: true
  jumbotronContext:
    heading: Wat is actief openbaar?
    subheading: Overheidsdocumenten
  jumbotron2Context:
    heading: Welke overheidsdocumenten zijn actief openbaar?
    hstyle: h2
    modifier: transparent
