---
label: Verdr. - Wizard 1
status: ready
context:
  header:
    file: logo.svg
    alt: Logo Overheid.nl, ga naar de startpagina
    language: true
  navVerdragContext:
    id: 2
    items:
    - title: Basisgegevens
      active: true
      sub: true
      subItems:
        - stitle: Algemeen
        - stitle: Koninkrijk
          sactive: true
        - stitle: Partijen
        - stitle: Uitbreidingen
    - title: Voorbehouden, verklaringen en bezwaren
    - title: Wijzigingen
  stepsContext:
    steps:
      - title: 1. Emailadres
        active: true
      - title: 2. Verdragen selecteren
      - title: 3. Samenvatting
  inputEmail:
    fieldPlaceholder: Uw emailadres
    fieldLabelVisible: true
    fieldLabel: E-mailadres
  disclaimer:
    content: <p>Staatsblad, Staatscourant en Tractatenblad worden met ingang van 1 juli 2009 als pdf-bestanden uitgegeven. De hier aangeboden pdf-bestanden van deze bladen vormen de formele bekendmakingen in de zin van de Grondwet. Voor publicaties van vóór deze datum geldt dat alleen de in papieren vorm uitgegeven bladen formele status hebben; de hier aangeboden elektronische versies daarvan worden bij wijze van service aangeboden.</p>
