---
label: SGD - Publicaties
status: ready
context:
  header:
    file: logo.svg
    alt: Overheid.nl logo
    navLinks:
    - url: '#'
      text: SGD
      className: is-active
    - url: '#'
      text: '...'
    skipLinks: false
    metaLinks:
      - text: Gebruiker
        class: icon icon--profile
        nonlink: true
      - url: "#"
        text: Uitloggen
        class: button button--logout
    youAreHere:
      - text: Externe Beheersite
  skipLinks:
    skipLinks:
      - url: '#content'
        text: Direct naar content
  topbar:
    navItems:
      - label: Beheersite
        href: '#'
        active: true
      - label: Digitaal Loket
        href: '#'
      - label: Stage BMS
        href: '#'
  breadcrumb:
    title: "U bent hier:"
    breadcrumb:
    - text: Home
      url: '/components/preview/templates-eb-homepage'
    - text: SGD
      url: '#'
    - text: Spoedpublicaties
  navToeContext:
    id: 2
    items:
    - title: SGD
      href: /components/preview/templates-eb-projectlanding
      active: true
      sub: true
      subItems:
        - stitle: Publicaties
          sactive: true
  searchPublications:
    showLabel: true
    label: Zoek publicatie
    placeholder: Identifier
    button: Zoek identifier
    modifierComponent: input-inputsubmit--s
  sortContext:
    modifier:
    columns: true
    amountPerPageFilter: true
    buttonDownload: false
    options:
    - label: Relevantie
      value: relevantie
      active: is-active
      singleSort: true
    - label: Identifier
      value: identifier
    - label: Titel
      value: titel
    - label: Documentsoort
      value: documentsoort
    - label: Vergaderjaar
      value: vergaderjaar
  tableResults:
    caption: false
    modifier: table--condensed
    items:
    - item:
      - column:
        type: Identifier
        value: '<a href="#">0000013938</a>'
      - column:
        type: Titel
        value: Planologische Kernbeslissing Waddenzee
      - column:
        type: Vergaderjaar
        value: 2021
      - column:
        type: Documentsoort
        value: PDF
      - column:
        type: Omschrijving
        value: '-'
    - item:
      - column:
        type: Identifier
        value: '<a href="#">0000013939</a>'
      - column:
        type: Titel
        value: Tweede Kamer der Staten-Generaal
      - column:
        type: Vergaderjaar
        value: 2020
      - column:
        type: Documentsoort
        value: PDF
      - column:
        type: Omschrijving
        value: '-'
