---
label: Password sterkte
status: ready
context:
  id: 1
  newPWInput:
    modifier:
    id: 344
    type: password
    class: js-passwordstrength__input
    fieldLabel: Nieuw wachtwoord
    fieldLabelVisible: true
    labelmodifier: accent
    fieldInstruction:
    fieldPlaceholder: Nieuw wachtwoord
    fieldDescribedby: strengthcontainer1
  regexContainer:
    id: strengthcontainer1
    description: '<p>Het wachtwoord dient te voldoen aan de volgende beveiligingseisen:</p>'
    regexOptions:
      - id: 1
        regex: (?=.{12,})
        label: Minimaal 12 tekens
      - id: 2
        regex: (?=.*[A-Z])
        label: Minimaal 1 hoofdletter
      - id: 3
        regex: (?=.*[a-z])
        label: Minimaal 1 kleine letter
      - id: 4
        regex: (?=.*[0-9])
        label: Minimaal 1 cijfer
      - id: 5
        regex: "[!@#$%^&*(),.?:{}|<>]"
        label: Minimaal 1 leesteken
  regexContainerDuplicate: false
variants:
  - name: With duplicate
    status: ready
    context:
      id: 1
      newPWInput:
        modifier:
        id: 2
        type: password
        class: js-passwordstrength__input
        fieldLabel: Nieuw wachtwoord
        fieldLabelVisible: true
        labelmodifier: accent
        fieldInstruction:
        fieldPlaceholder: Nieuw wachtwoord
      regexContainer:
        description: '<p>Het wachtwoord dient te voldoen aan de volgende beveiligingseisen:</p>'
        regexOptions:
          - id: 1
            regex: (?=.{12,})
            label: Minimaal 12 tekens
          - id: 2
            regex: (?=.*[A-Z])
            label: Minimaal 1 hoofdletter
          - id: 3
            regex: (?=.*[a-z])
            label: Minimaal 1 kleine letter
          - id: 4
            regex: (?=.*[0-9])
            label: Minimaal 1 cijfer
          - id: 5
            regex: "[!@#$%^&*(),.?:{}|<>]"
            label: Minimaal 1 leesteken
      regexContainerDuplicate: true
