---
label: identifiernl - Homepage
status: ready
context:
  header:
    file: logo.svg
    alt: Logo Overheid.nl, ga naar de startpagina
  jumbotronContext:
    heading: Zoek een URI
    subheading: URI resolver
    intro: Doorzoek hier de informatie in de collecties van Overheid.nl op basis van een Uniform Resource Identifier (URI).
    centered: true
    headingcentered: true
    size: medium
    prefixContext:
      modifier: input-text--medium
      modifier2: input-text__prefix--medium
      prefix: true
      type: text
      prefixLabel: https://identifier-tst.overheid.nl
    formalertContext:
      modifier: alert--warning
      text: De opgegeven URI is ongeldig.
