---
name: omtrent ONL inno v1
label: Omtrent
status: ready
context:
  header:
    navLinks: false
    metaLinks:
      - url: 'https://www.mijnoverheid.nl'
        text: MijnOverheid.nl
    youAreHere:
      - text: wegwijzer naar informatie en diensten van alle overheden
  breadcrumb:
    breadcrumb:
      - text: Overheid.nl
        url: '#'
      - text: Gemeente Rotterdam
  linkIntro:
    text: Contactgegevens gemeente Rotterdam
  mapContext:
    modifier: h-400
    controls: false
  rowActueel:
    modifier: row--spacer 
    header:
      heading: Actueel in de Gemeente Rotterdam
      headingType: h2
      subheading: Het laatste nieuws
    listBoub:
      items:
        - content: <a href="#">Aangevraagde omgevingsvergunning George Hintzenweg 89</a> <small>24-08-2022 09:06  |  Omgevingsvergunning</small>
        - content: <a href="https://www.rijksoverheid.nl">Kennisgeving ontwerpbeschikking Franciscus Gasthuis & Vlietland, locatie Gasthuis (9999249670)</a> <small>24-08-2022 09:06  |  Omgevingsvergunning</small>
        - content: <a href="#">Vergunning kamerbewoning onder de overgangsbepaling voor bestaande situaties van kamerbewoning Den Hertigstraat 37C</a> <small>24-08-2022 09:06  |  Omgevingsvergunning</small>
        - content: <a href="#">Vergunning kamerbewoning onder de overgangsbepaling voor bestaande situaties van kamerbewoning Den Hertigstraat 37C</a> <small>24-08-2022 09:06  |  Omgevingsvergunning</small>
        - content: <a href="#">Vergunning kamerbewoning onder de overgangsbepaling voor bestaande situaties van kamerbewoning Den Hertigstraat 37C</a> <small>24-08-2022 09:06  |  Omgevingsvergunning</small>
    listCvdr:
      items:
        - content: <a href="#">2012-2</a> <small>24-08-2022 09:06  |  Hoogheemraadschap van Delfland</small>
        - content: <a href="#">Namen van straten enz.</a> <small>24-08-2022 09:06  |  Veiligheidsregio Rotterdam-Rijnmond</small>
        - content: <a href="#">Aansluitverordening riolering 2012</a> <small>24-08-2022 09:06  |  Omgevingsdienst Haaglanden</small>
        - content: <a href="#">Aansluitverordening riolering 2012</a> <small>24-08-2022 09:06  |  Omgevingsdienst Haaglanden</small>
        - content: <a href="#">Namen van straten enz. Beijerlandse Passage</a> <small>24-08-2022 09:06  |  Omgevingsdienst Haaglanden</small>
    linkCta1:
      text: Alle Berichten over uw buurt
    linkCta2:
      text: Alle lokale wet- en regelgeving
  linkTerug:
    text: Zoek opnieuw
  rowDiensten:
    header:
      heading: Diensten van de gemeente Rotterdam
      headingType: h2
      subheading: Hoe kunnen we u helpen?
    listDiensten:
      items:
      - content: <h3 class="list__heading"><a href="#">Sociale zekerheid</a></h3><p>Uitkeringen, bijstand, kinderbijslag, gastouder, kinderopvang, subsidies, vergoedingen rondom studie, werk en inkomen, schulden, zorgverlof.</p>
      - content: <h3 class="list__heading"><a href="#">Verkeer</a></h3><p>Vergunningen, APK, scheepvaart, gehandicaptenparkeerplaats, autogordel en kinderzitje, vaarbewijs, kenteken, rijbewijs, registratie voertuigen, taxi.</p>
      - content: <h3 class="list__heading"><a href="#">Wonen</a></h3><p>Asbest, brandveiligheid, vergunningen, ongedierte- en onkruidbestrijding, starterslening, urgentiebewijs, verhuurdersverklaring, welstand, woning zoeken.</p>
      - content: <h3 class="list__heading"><a href="#">Zorg en gezondheid</a></h3><p>Begraven en cremeren, opname, geneesmiddelen, thuiszorg, jeugdhulp, mantelzorg, woonvoorziening, pgb, zorgverzekering en zorgtoeslag.</p>
  jumbotron2Context:
    modifier: slim
    heading: Meld u aan voor Berichten over uw buurt!
    h: h2
    subheading: Altijd op de hoogte van wat er in uw buurt gebeurt?
    centered: true
    headingcentered: true
    inputNewsletter:
      label: Uw e-mailadres
      showLabel: true
      placeholder: mail@adres.nl