---
label: CUP - Content
status: ready
context:
  header:
    file: logo.svg
    alt: Logo Overheid.nl, ga naar de startpagina
    language: true
    skipLinks:
      - url: '#content'
        text: Direct naar content

