---
name: omtrent ONL inno v1
label: omtrent (inno v1)
status: ready
context:
  headerContext:
    metaLinks:
      - url: 'https://www.mijnoverheid.nl'
        text: MijnOverheid.nl
  breadcrumb:
    breadcrumb:
      - text: Overheid.nl
        url: '#'
      - text: Gemeente Rotterdam
  jumbotronContext:
    heading: Gemeente Rotterdam
    subheading: Passende subtitel
    centered: true
    size: semimedium
    backlink:
      title: Zoek opnieuw
      href: '#'
    inputSearchContext:
      id: 87656
      fieldPlaceholder: Zoekwoord of zinsdeel
      fieldLabel: Zoek op postcode
      fieldLabelVisible: true
      name: searchcr
      labelmodifier: medium
      modifier: input-text--searchmedium
    btnSubmit:
      text: Zoek iets
      button: true
      type: submit
  buttonCtaGegevens:
    text: Bekijke alle gegevens
    action: http://www.overheid.nl/roo
    anchor: true
  mapContext:
    modifier: h-400
    controls: false
  blockIntro:
    id: 1
    heading: Actueel in de Gemeente Rotterdam
    htype: 2
    subheading: Het laatste nieuws
  listBoub:
    items:
      - content: <a href="#">Meldingen - Sloopmelding ingediend, Roggekamp 135 te Den Haag</a>
      - content: <a href="#">Meldingen - Sloopmelding ingediend, Roggekamp 44 te Den Haag</a>
      - content: <a href="#">Aanvraag omgevingsvergunning (kenmerk 787474) Waalhofflaan 6 Voorburg uitbreiden van het bestaande dakterras</a>
      - content: <a href="#">Omgevingsvergunning - Aangevraagd, Stuyvesantstraat 95 te Den Haag</a>
      - content: <a href="#">Aanvraag omgevingsvergunning (kenmerk 787551) Populierendreef 956 Voorburg plaatsen van een dakkapel in het voordakvlak van de woning</a>
  listCvdr:
    items:
      - content: <a href="#">Financiële verordening provincie Noord-Holland</a>
      - content: <a href="#">Algemene Subsidieverordening Zwolle</a>
      - content: <a href="#">Verordening rekenkamercommissie BUCH 2018</a>
      - content: <a href="#">Gemeenschappelijke Regeling Regionaal Archief Rivierenland 2016</a>
      - content: <a href="#">Regeling gebruik dienstauto door algemeen directeur Noord-Brabant</a>
  listDiensten:
    items:
      - content: <a href="#">Voorkeursrecht van de gemeente</a>
      - content: <a href="#">Rioolverstopping</a>
      - content: <a href="#">Echtscheiding/ontbinding partnerschap</a>
      - content: <a href="#">Inlichtingen uit de BRP voor deurwaarders aanvragen</a>
      - content: <a href="#">Huwelijk en partnerschap voor Nederlanders die in het buitenland wonen melden</a>
  linkCta1:
    text: Alle Berichten over uw buurt
  linkCta2:
    text: Alle lokale wet- en regelgeving
  linkCta3:
    text: Alle diensten
  blockContact:
    heading: Neem contact op
    subheading: Vragen?
    linkInternet:
      text: www.rotterdam.nl
      action: www.rotterdam.nl
      external: true
  jumbotron2Context:
    modifier: slim
    heading: Meld je aan voor de mail service
    h: h2
    subheading: Automatisch op de hoogte blijven van gebeurtenissen in uw buurt?
    centered: true
    headingcentered: true