---
title: Verschilmarkering switcher
status: ready
context:
  content: U bekijkt een publicatie met
  modal:
    initClosed: true
    openButton: wijzigingen
    buttonAriaLabel: Lees meer over de wijzigingen
    buttonModifier: button--inline
    modalContent: '<h2>Verschilmarkering</h2><p>Deze publicatie bevat verschilmarkering t.o.v. eerdere regelingtekst. Tekst en afbeeldingen die worden toegevoegd zijn onderstreept en groen gemarkeerd, of van een groen kader voorzien. Tekst en afbeeldingen die worden verwijderd zijn doorgestreept en rood gemarkeerd, of van een rood kader voorzien.</p><p>De publicatie wordt standaard getoond met verschilmarkering. Door te kiezen voor ‘Was’ of ‘Wordt’ kunt u de voormalige of vernieuwde tekst op zichzelf bekijken.</p>'
  options:
    - option:
        toast: 'true'
        isActive: true
        toastContext:
          id: 1
          dataAttributes: "data-controller-value='all'"
          isPressed: true
          trigger:
            label: Verschilmarkering
          message:
            variant: success
            text: U bekijkt deze publicatie nu met verschilmarkering.
    - option:
        toast: 'true'
        toastContext:
          id: 2
          dataAttributes: "data-controller-value='del'"
          trigger:
            label: Was
          message:
            variant: wa
            text: U bekijkt deze publicatie nu met de voormalige tekst.
    - option:
        label: Wordt
        dataAttributes: "data-controller-value='ins'"
  