---
label: CVDR - Wettechnischegegevens
status: ready
context:
  header:
    file: logo.svg
    alt: Overheid.nl logo
    language: true
    skipLinks:
      - url: '#content'
        text: Direct naar content
  navWetContext:
    id: 2
    items:
    - title: Wettechnische gegevens
      href: ""
      sub: false
      sactive: sactive
  navToeContext:
    id: 3
    items:
    - title: Toon regelingtekst
  tt1:
    id: 1453
    label: Help?
    content: Dit overzicht bevat alleen gepubliceerde versies.
  alertFoutief:
    heading: Ziet u een fout in deze regeling?
    text: '<p>Bent u van mening dat de inhoud niet juist is? Neem dan contact op met de organisatie die de regelgeving heeft gepubliceerd. Deze organisatie is namelijk zelf verantwoordelijk voor de inhoud van de regelgeving. De naam van de organisatie ziet u bovenaan de regelgeving. De contactgegevens van de organisatie kunt u hier opzoeken: almanak.overheid.nl.</p><p>Werkt de website of een link niet goed? Stuur dan een e-mail naar <a href="mailto:regelgeving@overheid.nl">regelgeving@overheid.nl</a></p>'
    modifier: alert--success alert--large icon--document
  pageactions:
    items:
    - link: '#'
      text: Permalink
      icon: icon-permalink.svg
      modal: true
    - link: '#'
      text: Fout in deze regeling
      icon: icon-alert-blue.svg
    - link: '#'
      text: Downloaden
      icon: icon-download.svg
    - link: '#'
      text: Printen
      icon: icon-print.svg
