---
label: CVDR - Contentpagina
status: ready
context:
  header:
    file: logo.svg
    alt: Overheid.nl logo
    language: true
    skipLinks:
      - url: '#content'
        text: Direct naar content
  navToeContext:
    id: 3
    items:
    - title: Regeling
      sub: true
      active: true
      subItems:
      - stitle: Regeling tekst
        href: "#section-1"
        sactive: true
      - stitle: Wettechnische gegevens
        href: "#section-2"
  alertFoutief:
    heading: Ziet u een fout in deze regeling?
    text: Meld het ons op <a href="mailto:regelgeving@overheid.nl">regelgeving@overheid.nl</a>
    modifier: alert--success alert--large icon--document
  pageactions:
    items:
    - link: '#'
      text: Permalink
      icon: icon-permalink.svg
      modal: true
    - link: '#'
      text: Fout in deze regeling
      icon: icon-alert-blue.svg
    - link: '#'
      text: Downloaden
      icon: icon-download.svg
    - link: '#'
      text: Printen
      icon: icon-print-blue.svg
  tablecontainer1:
    topbar:
      modifier: table-topbar--alignleft
      items:
      - text: Toon volledige tabel
        href: '#'
        class: button icon-bg icon--fullscreen
