---
label: CVDR - Contentpagina tabel
status: ready
context:
  header:
    file: logo.svg
    alt: Logo Overheid.nl, ga naar de startpagina
    language: true
    skipLinks:
      - url: '#content'
        text: Direct naar content
  terugnaarContext:
    text: Terug naar de vorige pagina
  breadcrumb:
    breadcrumb:
      - text: Zoeken
        url: '#'
      - text: Zoekresultaten
        url: '#'
      - text: Regeling
        url: '#'
      - text: Naam van de tabel
