---
label: CVDR - Contentpagina
status: ready
context:
  header:
    file: logo.svg
    alt: Logo Overheid.nl, ga naar de startpagina
    language: true
    skipLinks:
      - url: '#content'
        text: Direct naar content
  navToeContext:
    id: 3
    items:
    - title: Regeling tekst
      href: "#"
      active: true
      sactive: true
    - title: Wetstechnische informatie
      href: "#section-2"
  alertFoutief:
    heading: Ziet u een fout in deze regeling?
    text: Meld het ons op <a href="mailto:regelgeving@overheid.nl">regelgeving@overheid.nl</a>
    modifier: alert--success alert--large icon--document
  pageactions:
    items:
    - link: '#'
      text: Permalink
      icon: icon-permalink.svg
      modal: true
    - link: '#'
      text: Fout in deze regeling
      icon: icon-alert-blue.svg
    - link: '#'
      text: Downloaden
      icon: icon-download.svg
    - link: '#'
      text: Printen
      icon: icon-print-blue.svg
  tablecontainer1:
    topbar:
      modifier: table-topbar--alignleft
      items:
      - text: Toon volledige tabel
        href: '#'
        class: button icon-bg icon--fullscreen
