---
label: CVDR - Regeling
status: ready
context:
  header:
    file: logo.svg
    alt: Logo Overheid.nl, ga naar de startpagina
    language: true
    skipLinks:
      - url: '#content'
        text: Direct naar content
  navToeContext:
    id: 3
    items:
    - title: Regeling tekst
      href: "#"
      active: true
      sactive: true
    - title: Wetstechnische informatie
      href: "#section-2"
  pageactions:
    items:
    - link: '#'
      text: Permalink
      icon: icon-permalink.svg
      modal: true
    - link: '#'
      text: Downloaden
      icon: icon-download.svg
    - link: '#'
      text: Printen
      icon: icon-print-blue.svg
      actionPrint: true
  tablecontainer1:
    topbar:
      modifier: table-topbar--alignleft
      items:
      - text: Toon volledige tabel
        href: '#'
        class: button icon-bg icon--fullscreen
  alertFoutief:
    heading: Ziet u een fout in deze regeling?
    text: '<p>Bent u van mening dat de inhoud niet juist is? Neem dan contact op met de organisatie die de regelgeving heeft gepubliceerd. Deze organisatie is namelijk zelf verantwoordelijk voor de inhoud van de regelgeving. De naam van de organisatie ziet u bovenaan de regelgeving. De contactgegevens van de organisatie kunt u hier opzoeken: almanak.overheid.nl.</p><p>Werkt de website of een link niet goed? Stuur dan een e-mail naar <a href="mailto:regelgeving@overheid.nl">regelgeving@overheid.nl</a></p>'
    modifier: alert--success alert--large icon--document
