---
label: Toast
status: ready
context:
  id: 1
  debug: true
  trigger:
    label: Toon toast
    ariaLabel: Toon toast
  message:
    variant: success
    text: U bekijkt deze publicatie nu met de voormalige tekst.
