---
label: Aanm. - Stap 3
status: prototype
context:
  header:
    file: logo.svg
    alt: Overheid.nl logo
  breadcrumbAttenderen:
    breadcrumb:
    - text: Home
      url: '#'
    - text: Berichtgeving
      url: '#'
    - text: Berichten over uw buurt
  straalContext:
    options:
    - id: radio-1
      text: 250 meter
      name: radio-group-1
      checked: checked
      value: 250
    - id: radio-2
      text: 500 meter
      name: radio-group-1
      value: 500
    - id: radio-3
      text: 1000 meter
      name: radio-group-1
      value: 1000
    - id: radio-4
      text: 1500 meter
      name: radio-group-1
      value: 1500
    - id: radio-5
      text: 3000 meter
      name: radio-group-1
      value: 3000
    - id: radio-6
      text: Hele gemeente 'Den Haag'
      name: radio-group-1
      value: "Gemeente Den Haag"
      dataattributes:
        - data: data-kpm-rangetype
          value: gemeente
  mapContext:
    modifier: h-400
    controls: false
  rondomadresContext:
    id: 98766
    type: span
    linkText: Kies opties voor rondom een adres
    linkTextActive: Wijzig selectie
    modalTitle: Rondom een adres
    selectAll: true
    selectAllID: 98773
    selectAllType: opties
    selectAllHideCount: true
    selectAllLabel: Kies alle 
    selectAllOnMain:
      label: Kies alle opties
    maxShow: 3
    multilevel: true
    Options:
      - Option: 15151
        id: 15151
        title: Nederland
        short: Nederland
        checkAll: true
        OptionsSubs:
          - OptionsSub: 11776
            id: 11776
            title: NederlandSub1
            short: NederlandSub1
            checked: checked
          - OptionsSub: 12776
            id: 12776
            title: NederlandSub2
            short: NederlandSub2
      - Option: 27761111
        id: 27761111
        title: Duitsland
        short: Duitsland
        isSingle: true
      - Option: 2776
        id: 2776
        title: Frankrijk
        short: Frankrijk
        checkAll: true
        OptionsSubs:
          - OptionSub: 21776
            id: 21776
            title: FrankrijkSub1
            short: FrankrijkSub1
          - OptionSub: 22776
            id: 22776
            title: FrankrijkSub2
            short: FrankrijkSub2
  voorlichtingContext:
    id: 21
    type: span
    linkText: Kies opties voor voorlichting
    linkTextActive: Wijzig selectie
    modalTitle: Voorlichting
    selectAll: true
    selectAllID: 987731
    selectAllType: opties
    selectAllHideCount: true
    selectAllLabel: Kies alle
    selectAllOnMain:
      label: Kies alle opties
    maxShow: 3
    Options:
      - Option: 1
        id: 1237222222
        title: Afvalinzameling
        short: Afvalinzameling
      - Option: 2
        id: 2237231232131
        title: Inspraak
        short: Inspraak
      - Option: 3
        id: 3237
        title: Openingstijden
        short: Openingstijden
      - Option: 122222222
        id: 12372329
        title: Verkiezingen
        short: Verkiezingen
      - Option: 222222222222
        id: 22371231231
        title: Andere voorlichtingsinformatie
        short: Andere voorlichtingsinformatie
  voorschriftenContext:
    linkText: Kies opties over voorschriften & beleid
    id: 23
    modalTitle: Voorschriften & beleid
    maxShow: 3
    required: true
    selectAll: true
    selectAllID: 9880
    selectAllType: opties
    selectAllHideCount: true
    selectAllLabel: Kies alle
    selectAllOnMain:
      label: Kies alle opties
    type: span
    Options:
      - Option: 1
        id: 123766666
        title: Beleidsregel
        short: Beleidsregel
      - Option: 2
        id: 223723321312
        title: Algemeen verbindend voorschrift (verordering)
        short: Algemeen verbindend voorschrift (verordering)
      - Option: 3
        id: 3223
        title: Vergadering of stuk van het bestuur
        short: Vergadering of stuk van het bestuur
      - Option: 12222222
        id: 12372
        title: Ander besluit van algemene strekking
        short: Ander besluit van algemene strekking
      - Option: 22222222222
        id: 2237122312
        title: Overige overheidsinformatie
        short: Overige overheidsinformatie
  checkallOverheidsorganisatiesContext:
    id: 1
    label: overheidsorganisaties
    checkboxes:
      options:
      - id: checkbox-20
        text: Gemeente
        name: onderwerp
      - id: checkbox-21
        text: Provincie
        name: onderwerp
      - id: checkbox-22
        text: Regionaal Samenwerkingsorgaan
        name: onderwerp
      - id: checkbox-23
        text: Rijkswaterstaat
        name: onderwerp
      - id: checkbox-24
        text: Waterschap
        name: onderwerp
  jumbotronContext:
    heading: Over welke betrekkingen wilt u meldingen ontvangen?
    subheading: Kies uw meldingen
    intro: Kies voor een straal en voorkeursinstellingen om voor u relevante informatie te ontvangen op mail@koop.overheid.nl
    centered: true
    size: semimedium
    backlink:
      title: Wijzig e-mailadres
      href: '#'
    inputPostcodeContext:
      modifier: input-text--medium
      labelmodifier: accent
      id: 1
      value: 2453EH
      fieldLabel: Postcode
      fieldLabelVisible: true
      fieldInstruction:
      fieldPlaceholder: Bijv. 2453EH
      required: true
      patterntype: zipcode
      title: Vul een geldige postcode in, 4 cijfers en 2 letters (bijv. 1234AB)
    inputHuisnummerContext:
      modifier: input-text--medium
      labelmodifier: accent
      id: 2
      fieldLabel: Huisnummer
      fieldLabelVisible: true
      fieldInstruction:
      fieldPlaceholder: 52
      value: 52
    buttonSubmit:
      id: 123
      text: Adres ophalen
      button: true
      modifier: button--primary form__button
