---
label: Aanm. - Stap 3
status: prototype
context:
  header:
    file: logo.svg
    alt: Overheid.nl logo
  breadcrumbAttenderen:
    breadcrumb:
    - text: Home
      url: '#'
    - text: Berichtgeving
      url: '#'
    - text: Berichten over uw buurt
  straalContext:
    options:
    - id: radio-1
      text: 250 meter
      name: radio-group-1
      checked: checked
      value: 250
    - id: radio-2
      text: 500 meter
      name: radio-group-1
      value: 500
    - id: radio-3
      text: 1000 meter
      name: radio-group-1
      value: 1000
    - id: radio-4
      text: 1500 meter
      name: radio-group-1
      value: 1500
    - id: radio-5
      text: 3000 meter
      name: radio-group-1
      value: 3000
    - id: radio-6
      text: Hele gemeente 'Den Haag'
      name: radio-group-1
      value: "Gemeente Den Haag"
      dataattributes:
        - data: data-kpm-rangetype
          value: gemeente
  mapContext:
    modifier: h-400
    controls: false
  rondomadresContext:
    id: 98766
    type: span
    linkText: Kies opties voor rondom een adres
    linkTextActive: Wijzig selectie
    modalTitle: Rondom een adres
    selectAll: true
    selectAllID: 98773
    selectAllType: opties
    selectAllHideCount: true
    selectAllLabel: Kies alle 
    selectAllOnMain:
      label: Kies alle opties
    maxShow: 3
    multilevel: true
    buttonSubmitLabel: Selecteren
    Options:
      - Option: 15151
        id: 15151
        title: Alle omgevingsvergunning en -melding
        short: Alle omgevingsvergunning en -melding
        checkAll: true
        OptionsSubs:
          - OptionsSub: 11776
            id: 11776
            title: Bouwen
            short: Bouwen
            checked: checked
          - OptionsSub: 12776
            id: 12776
            title: Kappen
            short: Kappen
          - OptionsSub: 127761
            id: 127761
            title: Slopen
            short: Slopen
          - OptionsSub: 127762
            id: 127762
            title: Ruimtelijke ordening
            short: Ruimtelijke ordening
          - OptionsSub: 127763
            id: 127763
            title: Milieu
            short: Milieu
          - OptionsSub: 127764
            id: 127764
            title: Uitweg en inrit
            short: Uitweg en inrit
          - OptionsSub: 1277641
            id: 1277641
            title: Reclame
            short: Reclame
          - OptionsSub: 1277642
            id: 1277642
            title: Natuur
            short: Natuur
          - OptionsSub: 1277643
            id: 1277643
            title: Brandveilig gebruik
            short: Brandveilig gebruik
      - Option: 2776111121
        id: 2776111121
        title: Verkeersbesluit of -mededeling
        short: Verkeersbesluit of -mededeling
        isSingle: true
      - Option: 2776111122
        id: 2776111122
        title: Evenementenvergunning
        short: Evenementenvergunning
        isSingle: true
      - Option: 2776111123
        id: 2776111123
        title: Evenementmelding
        short: Evenementmelding
        isSingle: true
      - Option: 2776111124
        id: 2776111124
        title: Ruimtelijk plan of omgevingsdocument
        short: Ruimtelijk plan of omgevingsdocument
        isSingle: true
      - Option: 2776111125
        id: 2776111125
        title: Exploitatievergunning
        short: Exploitatievergunning
        isSingle: true
      - Option: 2776111126
        id: 2776111126
        title: Exploitatiemelding
        short: Exploitatiemelding
        isSingle: true
      - Option: 2776111127
        id: 2776111127
        title: Vergunning voor activiteiten op of in oppervlaktewater
        short: Vergunning voor activiteiten op of in oppervlaktewater
        isSingle: true
      - Option: 2776111128
        id: 2776111128
        title: Melding van activiteiten op of in oppervlaktewater
        short: Melding van activiteiten op of in oppervlaktewater
        isSingle: true
      - Option: 2776111129
        id: 2776111129
        title: Andere vergunning
        short: Andere vergunning
        isSingle: true
      - Option: 2776111130
        id: 2776111130
        title: Andere beschikking
        short: Andere beschikking
        isSingle: true
      - Option: 2776111131
        id: 2776111131
        title: Andere melding
        short: Andere melding
        isSingle: true
  voorlichtingContext:
    id: 21
    type: span
    linkText: Kies opties voor voorlichting
    linkTextActive: Wijzig selectie
    modalTitle: Voorlichting
    selectAll: true
    selectAllID: 987731
    selectAllType: opties
    selectAllHideCount: true
    selectAllLabel: Kies alle
    selectAllOnMain:
      label: Kies alle opties
    maxShow: 3
    buttonSubmitLabel: Selecteren
    Options:
      - Option: 1
        id: 1237222222
        title: Afvalinzameling
        short: Afvalinzameling
      - Option: 2
        id: 2237231232131
        title: Inspraak
        short: Inspraak
      - Option: 3
        id: 3237
        title: Openingstijden
        short: Openingstijden
      - Option: 122222222
        id: 12372329
        title: Verkiezingen
        short: Verkiezingen
      - Option: 222222222222
        id: 22371231231
        title: Andere voorlichtingsinformatie
        short: Andere voorlichtingsinformatie
  voorschriftenContext:
    linkText: Kies opties over voorschriften & beleid
    id: 23
    modalTitle: Voorschriften & beleid
    maxShow: 3
    required: true
    selectAll: true
    selectAllID: 9880
    selectAllType: opties
    selectAllHideCount: true
    selectAllLabel: Kies alle
    selectAllOnMain:
      label: Kies alle opties
    type: span
    buttonSubmitLabel: Selecteren
    Options:
      - Option: 1
        id: 123766666
        title: Beleidsregel
        short: Beleidsregel
      - Option: 2
        id: 223723321312
        title: Algemeen verbindend voorschrift (verordering)
        short: Algemeen verbindend voorschrift (verordering)
      - Option: 3
        id: 3223
        title: Vergadering of stuk van het bestuur
        short: Vergadering of stuk van het bestuur
      - Option: 12222222
        id: 12372
        title: Ander besluit van algemene strekking
        short: Ander besluit van algemene strekking
      - Option: 22222222222
        id: 2237122312
        title: Overige overheidsinformatie
        short: Overige overheidsinformatie
  checkallOverheidsorganisatiesContext:
    id: 1
    label: overheidsorganisaties
    checkboxes:
      options:
      - id: checkbox-20
        text: Gemeente
        name: onderwerp
      - id: checkbox-21
        text: Provincie
        name: onderwerp
      - id: checkbox-22
        text: Regionaal Samenwerkingsorgaan
        name: onderwerp
      - id: checkbox-23
        text: Rijkswaterstaat
        name: onderwerp
      - id: checkbox-24
        text: Waterschap
        name: onderwerp
  jumbotronContext:
    heading: Over welke betrekkingen wilt u meldingen ontvangen?
    subheading: Kies uw meldingen
    intro: Kies voor een straal en voorkeursinstellingen om voor u relevante informatie te ontvangen op mail@koop.overheid.nl
    centered: true
    size: semimedium
    backlink:
      title: Wijzig e-mailadres
      href: '#'
    inputPostcodeContext:
      modifier: input-text--medium
      labelmodifier: accent
      id: 1
      value: 2453EH
      fieldLabel: Postcode
      fieldLabelVisible: true
      fieldInstruction:
      fieldPlaceholder: Bijv. 2453EH
      required: true
      patterntype: zipcode
      title: Vul een geldige postcode in, 4 cijfers en 2 letters (bijv. 1234AB)
    inputHuisnummerContext:
      modifier: input-text--medium
      labelmodifier: accent
      id: 2
      fieldLabel: Huisnummer
      fieldLabelVisible: true
      fieldInstruction:
      fieldPlaceholder: 52
      value: 52
    buttonSubmit:
      id: 123
      text: Adres ophalen
      button: true
      modifier: button--primary form__button
